### ISSUE TITLE
Test combinations of MILLISECS_PER_BLOCK and BLOCK_PROCESSING_VELOCITY

### ISSUE THREAD

**Issue by Sophia-Gold** [paritytech/polkadot-sdk#2607]
The parachain upgrade guide for async backing states 6s block times can be activated in a parachain runtime by:

> Either decrease `MILLISECS_PER_BLOCK` to 6000 or increase `BLOCK_PROCESSING_VELOCITY` to 2.`

However, in tick and glutton we use _both_ 6000 and 2. We should manually test all combinations of these parameters and correct the guide if necessary.

**Comment by Sophia-Gold** [comment]
Collator logs showing each combination producing stable 6s parachain blocks:

[`MILLISECS_PER_BLOCK = 6000` and `BLOCK_PROCESSING_VELOCITY = 2`](https://github.com/paritytech/polkadot-sdk/files/13572360/6000_2.log)

[`MILLISECS_PER_BLOCK = 6000` and `BLOCK_PROCESSING_VELOCITY = 1`](https://github.com/paritytech/polkadot-sdk/files/13572577/6000_1.log)

[`MILLISECS_PER_BLOCK = 12000` and `BLOCK_PROCESSING_VELOCITY = 2`](https://github.com/paritytech/polkadot-sdk/files/13572531/12000_2.log)

However, in the last case Aura panics on this assert: https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/aura/src/lib.rs#L419

```
2023-12-05 15:15:30.039  INFO tokio-runtime-worker sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent 0xd8be63c2ee7bd42416bce5698181e98adc53b2200feaa6ea3b7dedf697341907    
2023-12-05 15:15:30.039 ERROR tokio-runtime-worker runtime: [Parachain] panicked at /home/sophia/dev/polkadot-sdk/substrate/frame/aura/src/lib.rs:416:9:
assertion `left == right` failed: Timestamp slot must match `CurrentSlot`
  left: Slot(141817277)
 right: Slot(141817278)    
2023-12-05 15:15:30.039 DEBUG tokio-runtime-worker parachain::network-bridge-rx: [Relaychain] action="PeerConnected" peer_set=Collation version=2 peer=PeerId("12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm") role=Authority
2023-12-05 15:15:30.039  WARN tokio-runtime-worker sp_state_machine::overlayed_changes::changeset: [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2023-12-05 15:15:30.039  WARN tokio-runtime-worker sp_state_machine::overlayed_changes::changeset: [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2023-12-05 15:15:30.039  WARN tokio-runtime-worker basic-authorship: [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x27d27d - <unknown>!rust_begin_unwind
    1: 0x8d35 - <unknown>!core::panicking::panic_fmt::hb4d2bab71ee3dc34
    2: 0x901c - <unknown>!core::panicking::assert_failed_inner::hb300612112401eed
    3: 0x205876 - <unknown>!core::panicking::assert_failed::h40bf77b3d8265f28
    4: 0x1b0ee3 - <unknown>!frame_support::storage::transactional::with_transaction::h5b3bb930ba17989d
    5: 0xbea54 - <unknown>!environmental::local_key::LocalKey<T>::with::h044bf39e5b8cd293
    6: 0x23ff6b - <unknown>!<rococo_parachain_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h551461bca76d06a8
    7: 0x241848 - <unknown>!<rococo_parachain_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h165d921dab858a28
    8: 0x186bdd - <unknown>!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h631258c1ec3e4ad3
    9: 0x1bde76 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h65bc0633202d398c
   10: 0x246e78 - <unknown>!BlockBuilder_apply_extrinsic. Dropping.    
2023-12-05 15:15:30.040 ERROR tokio-runtime-worker runtime: [Parachain] panicked at /home/sophia/dev/polkadot-sdk/substrate/frame/timestamp/src/lib.rs:231:13:
Timestamp must be updated once in the block    
2023-12-05 15:15:30.040 DEBUG tokio-runtime-worker parachain::collator-protocol: [Relaychain] Advertising collation. relay_parent=0x1415a63882dd5d025cfab396da2b37b5cdb71554b543a111d2d7e5800155248e candidate_hash=0xa2828cdbba9ca5f26b08ba7acbf9d52f10302965105aca6d3dbe7cb3af9d5be0 peer_id=12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm traceID=216012790854831588776799417551197689135
2023-12-05 15:15:30.040 ERROR tokio-runtime-worker aura::cumulus: [Parachain] err=Error { inner: Proposing

Caused by:
    0: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
       WASM backtrace:
       error while executing at wasm backtrace:
           0: 0x27d27d - <unknown>!rust_begin_unwind
           1: 0x8d35 - <unknown>!core::panicking::panic_fmt::hb4d2bab71ee3dc34
           2: 0x22cd33 - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h4dd3cbc71ce2d0dc
           3: 0x1be33d - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::he7cda88b20171dd2
           4: 0x1be3ff - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::h19045d808f6221f7
           5: 0x246f32 - <unknown>!BlockBuilder_finalize_block
    1: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
       WASM backtrace:
       error while executing at wasm backtrace:
           0: 0x27d27d - <unknown>!rust_begin_unwind
           1: 0x8d35 - <unknown>!core::panicking::panic_fmt::hb4d2bab71ee3dc34
           2: 0x22cd33 - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h4dd3cbc71ce2d0dc
           3: 0x1be33d - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::he7cda88b20171dd2
           4: 0x1be3ff - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::h19045d808f6221f7
           5: 0x246f32 - <unknown>!BlockBuilder_finalize_block

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::new
   1: <cumulus_client_consensus_proposer::Proposer<B,T> as cumulus_client_consensus_proposer::ProposerInterface<B>>::propose::{{closure}}
   2: cumulus_client_consensus_aura::collators::lookahead::run::{{closure}}
   3: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
   4: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
   5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   6: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
   7: tokio::runtime::task::core::Core<T,S>::poll
   8: tokio::runtime::task::harness::Harness<T,S>::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run
  11: tokio::runtime::context::set_scheduler
  12: tokio::runtime::context::runtime::enter_runtime
  13: tokio::runtime::scheduler::multi_thread::worker::run
  14: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::raw::poll
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/alloc/src/boxed.rs:2007:9
  21: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library/std/src/sys/unix/thread.rs:108:17
  22: start_thread
  23: __clone3 }
```

I don't think this is a bug because the `slot_duration` is actually wrong. I've updated the parachain upgrade guide to recommend lowering `MILLISECS_PER_BLOCK` instead.
