### ISSUE TITLE
JSON-RPC: Missing Chainspec methods

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/polkadot-sdk#5539]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

Endpoint: wss://westend-people-rpc.polkadot.io

```log
[19:51:47.876] TRACE (#2): 1-2024-08-30T23:51:47.855Z->>-{"jsonrpc":"2.0","id":"1-2","method":"chainSpec_v1_chainName","params":[]}
[19:51:47.876] TRACE (#3): 1-2024-08-30T23:51:47.855Z->>-{"jsonrpc":"2.0","id":"1-3","method":"chainSpec_v1_genesisHash","params":[]}
[19:51:47.877] TRACE (#4): 1-2024-08-30T23:51:47.855Z->>-{"jsonrpc":"2.0","id":"1-4","method":"chainSpec_v1_properties","params":[]}
[19:51:48.431] TRACE (#14): 1-2024-08-30T23:51:48.427Z-<<-{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":"1-4"}
[19:51:48.439] ERROR (#0) getChainSpecData=565ms:
UnknownException: An unknown error occurred
    at new YieldableError (:1:28)
    at new UnknownException (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/effect/dist/esm/internal/core.js:1130:7)
    at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/effect/dist/esm/internal/core-effect.js:594:134)
    at processTicksAndRejections (:12:39)
    at getChainSpecData (/home/ryan/Documents/Repositories/paritytech/identity-backend/src/rpc.ts:22:14) {
  [cause]: RpcError: Method not found
      at new RpcError (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/substrate-client/dist/esm/client/RpcError.mjs:6:5)
      at onMessage (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/substrate-client/dist/esm/client/createClient.mjs:31:39)
      at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/logs-provider/dist/esm/with-logs-recorder.mjs:16:7)
      at onMessageProxy (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-sync-provider.mjs:23
:5)
      at <anonymous> (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/json-rpc-provider-proxy/dist/esm/get-sync-provider.mjs:61:20
)
      at _onMessage (/home/ryan/Documents/Repositories/paritytech/identity-backend/node_modules/@polkadot-api/ws-provider/dist/node/esm/ws-provider.mjs:22:39)
}
19:51:48.534] TRACE (#16): 1-2024-08-30T23:51:48.427Z-<<-{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":"1-2"}
[19:51:48.536] TRACE (#17): 1-2024-08-30T23:51:48.427Z-<<-{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":"1-3"}
```

### Steps to reproduce

Hit any of the chainspec_v1 endpoints

**Comment by ryanleecode** [comment]
@paritytech/subxt-team

**Comment by niklasad1** [comment]
Hey Ryan

It's fixed by https://github.com/paritytech/polkadot-sdk/pull/5205 but it probably not included in the deployed released but should available in the next release
