### ISSUE TITLE
Rococo benchmarks not working for `polkadot_runtime_parachains::paras_inherent`

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#5680]
(I know Rococo will retire soon, but I would better fix this before we switch to frame-omni-bencher: https://github.com/paritytech/polkadot-sdk/pull/5327)

So, because of `max_validators_per_core: Some(1),` https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/rococo/src/genesis_config_presets.rs#L211:
```
configuration: ConfigurationConfig {
			config: polkadot_runtime_parachains::configuration::HostConfiguration {
				scheduler_params: SchedulerParams {
					max_validators_per_core: Some(1),
					..default_parachains_host_configuration().scheduler_params
				},
				..default_parachains_host_configuration()
			},
		},
```
the benchmark [enter_backed_candidates_variable](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/runtime/parachains/src/paras_inherent/benchmarking.rs#L108-L110) generates value for `v` like `[(v, 2, 1)]`, which causes error [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/utils/frame/benchmarking-cli/src/pallet/command.rs#L305-L310), e.g. this CI job: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/7317555:
```
error: 
   0: Invalid input: `low` cannot be higher than `high`
```

it is possible to simulate locally in the branch: https://github.com/paritytech/polkadot-sdk/pull/5327 with:
```
cargo run --locked -p polkadot --features runtime-benchmarks -- benchmark pallet --chain rococo-dev --pallet "polkadot_runtime_parachains::paras_inherent" --extrinsic "enter_backed_candidates_variable" --steps 2 --repeat 1
```

How can/should we fix the roococo development genesis config for SchedulerParams/HostConfiguration to pass?

**Comment by bkontur** [comment]
this is working: https://github.com/paritytech/polkadot-sdk/pull/5327/commits/ab2a78df16083e5e13d16292af0887be5e18016f

**Comment by ordian** [comment]
Alternatively, we could patch polkadot-sdk to return 1 here
https://github.com/paritytech/polkadot-sdk/blob/8f6699beadc220503721db3e60d0cfaa21f81b64/polkadot/runtime/parachains/src/builder.rs#L320

**Comment by bkontur** [comment]
> Alternatively, we could patch polkadot-sdk to return 1 here
> 
> https://github.com/paritytech/polkadot-sdk/blob/8f6699beadc220503721db3e60d0cfaa21f81b64/polkadot/runtime/parachains/src/builder.rs#L320

@ordian I tried it, but actually it does not work with `1`, it gives another error:

```
unning `target/debug/polkadot benchmark pallet --chain rococo-dev --pallet 'polkadot_runtime_parachains::paras_inherent' --extrinsic enter_backed_candidates_variable --steps 2 --repeat 1`
2024-09-12 08:57:22.909  WARN main frame_benchmarking_cli::pallet::command: Using the chain spec instead of the runtime to generate the genesis state is deprecated. Please remove the `--chain`/`--dev`/`--local` argument, point `--runtime` to your runtime blob and set `--genesis-builder=runtime`. This warning may become a hard error any time after December 2024.    
2024-09-12 08:58:16.065  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:16.065  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:16.065  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:16.065  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:16.181  INFO main frame_benchmarking_cli::pallet::command: Loading WASM from genesis state    
2024-09-12 08:58:41.969  INFO main polkadot_sdk_frame::benchmark::pallet: [  0 % ] Starting benchmark: polkadot_runtime_parachains::paras_inherent::enter_backed_candidates_variable    
2024-09-12 08:58:43.283  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.283  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.283  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:43.284  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.298  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.298  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.298  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:43.299  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.314  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.314  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:43.314  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:43.314  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:46.122  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:58:47.591  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.591  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.591  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:47.591  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.606  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.606  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.606  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:47.606  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.623  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.623  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:47.623  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:47.623  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:50.440  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:58:51.797  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.798  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.798  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:51.798  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.812  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.813  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.813  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:51.813  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.827  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.828  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:51.828  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:51.828  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:54.644  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:58:54.676  INFO main polkadot_sdk_frame::benchmark::pallet: [  0 % ] Running  benchmark: polkadot_runtime_parachains::paras_inherent::enter_backed_candidates_variable(1 args) 1/2 1/1    
2024-09-12 08:58:55.985  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:55.986  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:55.986  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:55.986  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.000  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.001  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.001  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:56.001  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.016  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.016  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:56.016  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:58:56.016  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:58:58.832  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:59:00.205  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.205  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.205  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:00.206  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.220  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.220  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.220  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:00.221  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.235  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.235  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:00.235  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:00.236  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:03.033  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:59:04.368  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.368  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.368  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:04.368  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.383  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.383  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.383  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:04.383  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.398  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.399  WARN main runtime::parachains: Took active validators from set with wrong size    
2024-09-12 08:59:04.399  WARN main runtime::parachains: Took active validators from set with wrong size.    
2024-09-12 08:59:04.399  WARN main runtime::parachains: Took active validators from set with wrong size    
Pallet: "polkadot_runtime_parachains::paras_inherent", Extrinsic: "enter_backed_candidates_variable", Lowest values: [], Highest values: [], Steps: 2, Repeat: 1
Raw Storage Info
========
Storage: `ParaInherent::Included` (r:1 w:1)
Proof: `ParaInherent::Included` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `System::ParentHash` (r:1 w:0)
Proof: `System::ParentHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
Storage: `ParasShared::AllowedRelayParents` (r:1 w:1)
Proof: `ParasShared::AllowedRelayParents` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParasShared::CurrentSessionIndex` (r:1 w:0)
Proof: `ParasShared::CurrentSessionIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParaScheduler::AvailabilityCores` (r:1 w:1)
Proof: `ParaScheduler::AvailabilityCores` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParasShared::ActiveValidatorKeys` (r:1 w:0)
Proof: `ParasShared::ActiveValidatorKeys` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
Storage: `ParaInherent::OnChainVotes` (r:1 w:1)
Proof: `ParaInherent::OnChainVotes` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParasDisputes::Frozen` (r:1 w:0)
Proof: `ParasDisputes::Frozen` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParaInclusion::V1` (r:2 w:1)
Proof: `ParaInclusion::V1` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Dmp::DownwardMessageQueues` (r:1 w:1)
Proof: `Dmp::DownwardMessageQueues` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Dmp::DeliveryFeeFactor` (r:1 w:1)
Proof: `Dmp::DeliveryFeeFactor` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Hrmp::HrmpChannelDigests` (r:1 w:1)
Proof: `Hrmp::HrmpChannelDigests` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::FutureCodeUpgrades` (r:1 w:0)
Proof: `Paras::FutureCodeUpgrades` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Registrar::Paras` (r:1 w:0)
Proof: `Registrar::Paras` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `ParasDisputes::Disputes` (r:1 w:0)
Proof: `ParasDisputes::Disputes` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `ParaScheduler::SessionStartBlock` (r:1 w:0)
Proof: `ParaScheduler::SessionStartBlock` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParaScheduler::ValidatorGroups` (r:1 w:0)
Proof: `ParaScheduler::ValidatorGroups` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParaScheduler::ClaimQueue` (r:1 w:1)
Proof: `ParaScheduler::ClaimQueue` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `CoretimeAssignmentProvider::CoreDescriptors` (r:1 w:1)
Proof: `CoretimeAssignmentProvider::CoreDescriptors` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::CurrentCodeHash` (r:1 w:0)
Proof: `Paras::CurrentCodeHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::ParaLifecycles` (r:1 w:0)
Proof: `Paras::ParaLifecycles` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `MessageQueue::BookStateFor` (r:1 w:0)
Proof: `MessageQueue::BookStateFor` (`max_values`: None, `max_size`: Some(55), added: 2530, mode: `MaxEncodedLen`)
Storage: `ParasShared::ActiveValidatorIndices` (r:1 w:0)
Proof: `ParasShared::ActiveValidatorIndices` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `Session::DisabledValidators` (r:1 w:0)
Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
Storage: `ParasDisputes::Included` (r:0 w:1)
Proof: `ParasDisputes::Included` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Hrmp::HrmpWatermarks` (r:0 w:1)
Proof: `Hrmp::HrmpWatermarks` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::Heads` (r:0 w:1)
Proof: `Paras::Heads` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::UpgradeGoAheadSignal` (r:0 w:1)
Proof: `Paras::UpgradeGoAheadSignal` (`max_values`: None, `max_size`: None, mode: `Measured`)
Storage: `Paras::MostRecentContext` (r:0 w:1)
Proof: `Paras::MostRecentContext` (`max_values`: None, `max_size`: None, mode: `Measured`)

Median Slopes Analysis
========
2024-09-12 08:59:07.193  WARN main runtime::inclusion-inherent: ParentBlockRandomness did not provide entropy    
2024-09-12 08:59:07.221  INFO main polkadot_sdk_frame::benchmark::pallet: [  0 % ] Running  benchmark: polkadot_runtime_parachains::paras_inherent::enter_backed_candidates_variable(1 args) 2/2 1/1    

====================

Version: 1.15.1-237a578a1e4

   0: sp_panic_handler::panic_hook
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/primitives/panic-handler/src/lib.rs:166:18
   1: sp_panic_handler::set::{{closure}}
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/primitives/panic-handler/src/lib.rs:62:12
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
      std::panicking::rust_panic_with_hook
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   6: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   7: core::panicking::panic_bounds_check
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:275:5
   8: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/index.rs:249:10
   9: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/index.rs:18:9
      <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:2907:9
  10: frame_benchmarking::analysis::Analysis::median_slopes::{{closure}}
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/frame/benchmarking/src/analysis.rs:286:23
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/adapters/map.rs:89:28
  12: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/iter/macros.rs:230:27
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/adapters/map.rs:129:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/traits/iterator.rs:818:9
  15: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:3098:17
  16: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_extend.rs:26:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_from_iter.rs:33:9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:2972:9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/traits/iterator.rs:2004:9
  21: frame_benchmarking::analysis::Analysis::median_slopes
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/frame/benchmarking/src/analysis.rs:274:16
  22: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::print_summary
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/utils/frame/benchmarking-cli/src/pallet/command.rs:899:6
  23: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::output
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/utils/frame/benchmarking-cli/src/pallet/command.rs:772:4
  24: frame_benchmarking_cli::pallet::command::<impl frame_benchmarking_cli::pallet::PalletCmd>::run_with_spec
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/utils/frame/benchmarking-cli/src/pallet/command.rs:510:3
  25: polkadot_cli::command::run::{{closure}}
             at /home/bparity/parity/aaa/polkadot-sdk/polkadot/cli/src/command.rs:463:8
  26: sc_cli::runner::Runner<C>::sync_run
             at /home/bparity/parity/aaa/polkadot-sdk/substrate/client/cli/src/runner.rs:142:3
  27: polkadot_cli::command::run
             at /home/bparity/parity/aaa/polkadot-sdk/polkadot/cli/src/command.rs:462:7
  28: polkadot::main
             at /home/bparity/parity/aaa/polkadot-sdk/polkadot/src/main.rs:31:2
  29: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  31: std::rt::lang_start::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
  32: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
      std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
      std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
      std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
      std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
      std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
      std::rt::lang_start_internal
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
  33: std::rt::lang_start
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
  34: main
  35: __libc_start_main
             at /build/glibc-LcI20x/glibc-2.31/csu/../csu/libc-start.c:308:16
  36: _start


Thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', substrate/frame/benchmarking/src/analysis.rs:286

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot-sdk/issues/new

```
