### ISSUE TITLE
Omni-node: fix manual seal + asset hub polkadot scenario

### ISSUE THREAD

**Issue by serban300** [paritytech/polkadot-sdk#5932]
When starting an asset hub polkadot node with manual seal:

```
polkadot-parachain --chain asset-hub-polkadot --dev-block-time 3000 --tmp
```

We get errors that go like:

```
2024-10-04 20:40:11 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x1be1 - <unknown>!rust_begin_unwind
    1: 0x199e - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b
    2: 0x16c3 - <unknown>!core::result::unwrap_failed::h9bf99bca88ba05dc
    3: 0x3b9e4 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::hb411780f0f813d4a
    4: 0x9a150 - <unknown>!<shell_runtime::Call as sp_runtime::traits::Dispatchable>::dispatch::hfa16958ca768b7fa
    5: 0x60b70 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::apply_extrinsic::h665bdef660f803fa
    6: 0x5efb3 - <unknown>!BlockBuilder_apply_extrinsic. Dropping.    
2024-10-04 20:40:11 [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /build/pallets/parachain-system/src/lib.rs:135:13  
```

I think the issue is that the version of the code that is in the chainspec is outdated and probably the Parachain data inherent is incompatible with what we mock. When you actually run a parachain node it doesn't matter if the code in the spec is outdated, because it connects to the peers and gets the on-chain version. But when you run with manual seal, it tries to run the version that's in the spec.  

So I think that the solution is to update the asset-hub-polkadot chainspec: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/chain-specs/asset-hub-polkadot.json using `chain-spec-builder update-code`.

**Comment by brunopgalvao** [comment]
```
polkadot-omni-node --chain ./chain_spec.json --dev
2025-01-26 12:40:33 polkadot-omni-node    
2025-01-26 12:40:33 ✌️  version 0.1.0-682f8cd22f5    
2025-01-26 12:40:33 ❤️  by Parity Technologies <admin@parity.io>, 2017-2025    
2025-01-26 12:40:33 📋 Chain specification: Custom    
2025-01-26 12:40:33 🏷  Node name: ready-aunt-2671    
2025-01-26 12:40:33 👤 Role: AUTHORITY    
2025-01-26 12:40:33 💾 Database: RocksDb at /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/substrateJzUAMc/chains/custom/db/full    
2025-01-26 12:40:33 assembling new collators for new session 0 at #0    
2025-01-26 12:40:33 assembling new collators for new session 1 at #0    
2025-01-26 12:40:34 [Parachain] assembling new collators for new session 0 at #0    
2025-01-26 12:40:34 [Parachain] assembling new collators for new session 1 at #0    
2025-01-26 12:40:34 [Parachain] 🔨 Initializing Genesis block/state (state: 0x8ed0…8d5d, header-hash: 0x1c1b…ddeb)    
2025-01-26 12:40:34 [Parachain]  creating SingleState txpool Limit { count: 8192, total_bytes: 20971520 }/Limit { count: 819, total_bytes: 2097152 }.    
2025-01-26 12:40:34 [Parachain] Using default protocol ID "sup" because none is configured in the chain specs    
2025-01-26 12:40:34 [Parachain] 🏷  Local node identity is: 12D3KooWRuDAg47ZTbCu3LgvbKzxG1a5hNW4E7YMov1KbVpuNpGg    
2025-01-26 12:40:34 [Parachain] Running libp2p network backend    
2025-01-26 12:40:34 [Parachain] local_peer_id=12D3KooWRuDAg47ZTbCu3LgvbKzxG1a5hNW4E7YMov1KbVpuNpGg
2025-01-26 12:40:34 [Parachain] 💻 Operating system: macos    
2025-01-26 12:40:34 [Parachain] 💻 CPU architecture: aarch64    
2025-01-26 12:40:34 [Parachain] 📦 Highest known block at #0    
2025-01-26 12:40:34 [Parachain] 〽️ Prometheus exporter started at 127.0.0.1:9615    
2025-01-26 12:40:34 [Parachain] Running JSON-RPC server: addr=127.0.0.1:9944,[::1]:9944    
2025-01-26 12:40:35 [Parachain] Failed to trigger bootstrap: No known peers.
2025-01-26 12:40:37 [Parachain] 🙌 Starting consensus session on top of parent 0x1c1b0a2cfba3e633b4f6fcce0453b6f9a80349fa7099514d7e9ac36c1f17ddeb (#0)    
2025-01-26 12:40:37 [Parachain] 🎁 Prepared block for proposing at 1 (4 ms) hash: 0x8ea0c31651e0f263dadf37ef989b7a41466e38f530aa5bb5d234925467dac49f; parent_hash: 0x1c1b…ddeb; end: NoMoreTransactions; extrinsics_count: 2    
2025-01-26 12:40:37 [Parachain] Consensus with no RPC sender success: CreatedBlock { hash: 0x8ea0c31651e0f263dadf37ef989b7a41466e38f530aa5bb5d234925467dac49f, aux: ImportedAux { header_only: false, clear_justification_requests: false, needs_justification: false, bad_justification: false, is_new_best: true }, proof_size: 0 }    
2025-01-26 12:40:37 [Parachain] 🏆 Imported #1 (0x1c1b…ddeb → 0x8ea0…c49f)    
2025-01-26 12:40:39 [Parachain] 💤 Idle (0 peers), best: #1 (0x8ea0…c49f), finalized #1 (0x8ea0…c49f), ⬇ 0 ⬆ 0    
2025-01-26 12:40:40 [Parachain] 🙌 Starting consensus session on top of parent 0x8ea0c31651e0f263dadf37ef989b7a41466e38f530aa5bb5d234925467dac49f (#1)    
2025-01-26 12:40:40 [Parachain] panicked at /Users/bruno/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cumulus-pallet-aura-ext-0.17.0/src/consensus_hook.rs:81:4:
authored blocks limit is reached for the slot    
2025-01-26 12:40:40 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2025-01-26 12:40:40 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.    
2025-01-26 12:40:40 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x30767e - parachain_template_runtime.wasm!rust_begin_unwind
    1: 0xc183 - parachain_template_runtime.wasm!core::panicking::panic_fmt::ha805e8982f263a58
    2: 0x254e6e - parachain_template_runtime.wasm!frame_support::storage::transactional::with_transaction::h93d38d0e0f3f2664
    3: 0x2cb00d - parachain_template_runtime.wasm!environmental::local_key::LocalKey<T>::with::hdda11b916fb4d777
    4: 0xd24be - parachain_template_runtime.wasm!<parachain_template_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h6aad09c7bec45f41
    5: 0xcf537 - parachain_template_runtime.wasm!<parachain_template_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::hf35d5a46cf65a5d2
    6: 0xf74aa - parachain_template_runtime.wasm!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h6ac2b662ddf4b3ce
    7: 0x25f1d0 - parachain_template_runtime.wasm!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::he8177a9daadc9978
    8: 0x26f7cc - parachain_template_runtime.wasm!BlockBuilder_apply_extrinsic. Dropping.    
2025-01-26 12:40:40 [Parachain] panicked at /Users/bruno/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cumulus-pallet-parachain-system-0.17.1/src/lib.rs:263:6:
set_validation_data inherent needs to be present in every block!    
2025-01-26 12:40:40 [Parachain] Consensus with no RPC sender encountered an error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed

```

I have ran into this issue following the new Polkadot Docs, specifically when I reach this section:
- https://docs.polkadot.com/tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template/#start-the-local-chain

Also, we should be using versions in the Polkadot Docs, instead of compiling off of `master` for `polkadot-sdk`, `chain-spec-builder`, `polkadot-sdk-parachain-template`, and `polkadot-omni-node`, that way debugging on StackExchange or Github is manageable.

**Comment by kianenigma** [comment]
Closing in fav of https://github.com/polkadot-developers/polkadot-docs/issues/327

**Comment by Kobra-Jamali** [comment]
Hi,
I am a newbie; I get the error below when I run a local node. Could you please assist me?

root@PGR9:~/parachain-template# polkadot-omni-node --chain ./chain_spec.json --dev
2025-02-01 23:59:55 polkadot-omni-node
2025-02-01 23:59:55 ✌️  version 0.1.0-23833ccee9c
2025-02-01 23:59:55 ❤️  by Parity Technologies <admin@parity.io>, 2017-2025
2025-02-01 23:59:55 📋 Chain specification: Custom
2025-02-01 23:59:55 🏷  Node name: shy-brain-3900
2025-02-01 23:59:55 👤 Role: AUTHORITY
2025-02-01 23:59:55 💾 Database: RocksDb at /tmp/substrateRuamYy/chains/custom/db/full
2025-02-01 23:59:57 assembling new collators for new session 0 at #0
2025-02-01 23:59:57 assembling new collators for new session 1 at #0
2025-02-02 00:00:01 [Parachain] assembling new collators for new session 0 at #0
2025-02-02 00:00:01 [Parachain] assembling new collators for new session 1 at #0
2025-02-02 00:00:03 [Parachain] 🔨 Initializing Genesis block/state (state: 0x8146…0b3d, header-hash: 0x54de…454d)
2025-02-02 00:00:03 [Parachain]  creating SingleState txpool Limit { count: 8192, total_bytes: 20971520 }/Limit { count: 819, total_bytes: 2097152 }.
2025-02-02 00:00:03 [Parachain] Using default protocol ID "sup" because none is configured in the chain specs
2025-02-02 00:00:03 [Parachain] 🏷  Local node identity is: 12D3KooWFaTJsrYM8s6ixfgithL4eV2u577HfD9MqD46RaWVxE8V
2025-02-02 00:00:03 [Parachain] Running libp2p network backend
2025-02-02 00:00:03 [Parachain] local_peer_id=12D3KooWFaTJsrYM8s6ixfgithL4eV2u577HfD9MqD46RaWVxE8V
2025-02-02 00:00:03 [Parachain] 💻 Operating system: linux
2025-02-02 00:00:03 [Parachain] 💻 CPU architecture: x86_64
2025-02-02 00:00:03 [Parachain] 💻 Target environment: gnu
2025-02-02 00:00:03 [Parachain] 💻 CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
2025-02-02 00:00:03 [Parachain] 💻 CPU cores: 4
2025-02-02 00:00:03 [Parachain] 💻 Memory: 12798MB
2025-02-02 00:00:03 [Parachain] 💻 Kernel: 6.8.0-52-generic
2025-02-02 00:00:03 [Parachain] 💻 Linux distribution: Ubuntu 24.04.1 LTS
2025-02-02 00:00:03 [Parachain] 💻 Virtual machine: yes
2025-02-02 00:00:03 [Parachain] 📦 Highest known block at #0
2025-02-02 00:00:03 [Parachain] Running JSON-RPC server: addr=127.0.0.1:9944,[::1]:9944
2025-02-02 00:00:03 [Parachain] 〽️ Prometheus exporter started at 127.0.0.1:9615
**2025-02-02 00:00:04 [Parachain] Failed to trigger bootstrap: No known peers.**
2025-02-02 00:00:06 [Parachain] 🙌 Starting consensus session on top of parent 0x54de8be9450f8bca535cda75f57c32a74784b415587209214ee91ca605e2454d (#0)
2025-02-02 00:00:06 [Parachain] 🎁 Prepared block for proposing at 1 (1 ms) hash: 0xb793ab6279d614f13e30bd74db01bc253aff93bb5f1a235f538a04a881506e30; parent_hash: 0x54de…454d; end: NoMoreTransactions; extrinsics_count: 2
2025-02-02 00:00:06 [Parachain] Consensus with no RPC sender success: CreatedBlock { hash: 0xb793ab6279d614f13e30bd74db01bc253aff93bb5f1a235f538a04a881506e30, aux: ImportedAux { header_only: false, clear_justification_requests: false, needs_justification: false, bad_justification: false, is_new_best: true }, proof_size: 0 }
2025-02-02 00:00:06 [Parachain] 🏆 Imported #1 (0x54de…454d → 0xb793…6e30)
2025-02-02 00:00:08 [Parachain] 💤 Idle (0 peers), best: #1 (0xb793…6e30), finalized #1 (0xb793…6e30), ⬇ 0 ⬆ 0
2025-02-02 00:00:09 [Parachain] 🙌 Starting consensus session on top of parent 0xb793ab6279d614f13e30bd74db01bc253aff93bb5f1a235f538a04a881506e30 (#1)
2025-02-02 00:00:09 [Parachain] panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cumulus-pallet-aura-ext-0.17.0/src/consensus_hook.rs:81:4:
authored blocks limit is reached for the slot
2025-02-02 00:00:09 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2025-02-02 00:00:09 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
**2025-02-02 00:00:09 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed**
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x30775b - parachain_template_runtime.wasm!rust_begin_unwind
    1: 0xc185 - parachain_template_runtime.wasm!core::panicking::panic_fmt::h9a80ea1ef931d1e0
    2: 0x24a154 - parachain_template_runtime.wasm!frame_support::storage::transactional::with_transaction::h3b03463ab081b4b5
    3: 0x2ccdb8 - parachain_template_runtime.wasm!environmental::local_key::LocalKey<T>::with::hfc890073c8783cb8
    4: 0xd251c - parachain_template_runtime.wasm!<parachain_template_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::hb70ebbc93f58a985
    5: 0xcf5a3 - parachain_template_runtime.wasm!<parachain_template_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h6de921a2e7febb4c
    6: 0xf7507 - parachain_template_runtime.wasm!<sp_runtime::generic::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra> as sp_runtime::traits::Applyable>::apply::h2ddb10b26b6db302
    7: 0x25f24e - parachain_template_runtime.wasm!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h8bccb3d79d404574
    8: 0x26f849 - parachain_template_runtime.wasm!BlockBuilder_apply_extrinsic. Dropping.
