### ISSUE TITLE
Panics with `Bad input data provided to validate_transaction: Codec error`

### ISSUE THREAD

**Issue by AndreiEres** [paritytech/polkadot-sdk#5936]
A Polkadot validator (1.16.0-87971b3e927) reported 439404 not continuous error messages between Sep 14 15:11:57 and Oct 04 23:56:26:
```
Bad input data provided to validate_transaction: Codec error 
2024-10-04 23:56:26 panicked at /build/relay/polkadot/src/lib.rs:2095:1:
```

<details>
<summary>More logs</summary>
<pre>
Oct 04 23:56:36 polkadot polkadot[253731]: 2024-10-04 23:56:36 🏆 Imported #22825876 (0x5fae…0dcc → 0x41bb…a0de)
Oct 04 23:56:35 polkadot polkadot[253731]: 2024-10-04 23:56:35 💤 Idle (37 peers), best: #22825875 (0x5fae…0dcc), finalized #22825873 (0x79fd…0a05), ⬇ 1.3MiB/s ⬆ 489.3kiB/s
Oct 04 23:56:30 polkadot polkadot[253731]: 2024-10-04 23:56:30 🏆 Imported #22825875 (0xd911…f18c → 0x5fae…0dcc)
Oct 04 23:56:30 polkadot polkadot[253731]: 2024-10-04 23:56:30 💤 Idle (37 peers), best: #22825874 (0xd911…f18c), finalized #22825872 (0xf165…09b0), ⬇ 1.2MiB/s ⬆ 796.4kiB/s
Oct 04 23:56:28 polkadot polkadot[253731]: 2024-10-04 23:56:28 Report 12D3KooWGJijhP6pDMJGGAPfjWWKLi5mTqsisiSZFV5nPTHnW8d7: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnect>
Oct 04 23:56:26 polkadot polkadot[253731]: Bad input data provided to validate_transaction: Codec error
Oct 04 23:56:26 polkadot polkadot[253731]: 2024-10-04 23:56:26 panicked at /build/relay/polkadot/src/lib.rs:2095:1:
Oct 04 23:56:36 polkadot polkadot[253731]: 2024-10-04 23:56:36 🏆 Imported #22825876 (0x5fae…0dcc → 0x41bb…a0de)
Oct 04 23:56:35 polkadot polkadot[253731]: 2024-10-04 23:56:35 💤 Idle (37 peers), best: #22825875 (0x5fae…0dcc), finalized #22825873 (0x79fd…0a05), ⬇ 1.3MiB/s ⬆ 489.3kiB/s
Oct 04 23:56:30 polkadot polkadot[253731]: 2024-10-04 23:56:30 🏆 Imported #22825875 (0xd911…f18c → 0x5fae…0dcc)
Oct 04 23:56:30 polkadot polkadot[253731]: 2024-10-04 23:56:30 💤 Idle (37 peers), best: #22825874 (0xd911…f18c), finalized #22825872 (0xf165…09b0), ⬇ 1.2MiB/s ⬆ 796.4kiB/s
Oct 04 23:56:28 polkadot polkadot[253731]: 2024-10-04 23:56:28 Report 12D3KooWGJijhP6pDMJGGAPfjWWKLi5mTqsisiSZFV5nPTHnW8d7: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnect>
Oct 04 23:56:26 polkadot polkadot[253731]: Bad input data provided to validate_transaction: Codec error
Oct 04 23:56:26 polkadot polkadot[253731]: 2024-10-04 23:56:26 panicked at /build/relay/polkadot/src/lib.rs:2095:1:
</pre>
</details>

It seems to be a known a harmless thing: https://github.com/paritytech/polkadot/issues/7555#issuecomment-1677746947

Shouldn't we translate it into a warning to avoid scaring validators?

**Comment by ScepticMatt** [comment]
We are getting a large number of these messages on an active validator on release [stable2409](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-stable2409)

```
Oct 17 09:11:16 dot1 taskset[1376352]: 2024-10-17 09:11:16 panicked at /build/relay/polkadot/src/lib.rs:2316:1:
Oct 17 09:11:24 dot1 systemd-journald[4038732]: [🡕] Suppressed 2038 messages from polkadot.service
```bash

**Comment by dbpatty** [comment]
Hi @AndreiEres,  I am also getting a large number of these messages. May I do anything to avoid this error message? I updated my nodes to the latest release (2412-1).

**Comment by bkchr** [comment]
This error is not problematic. It basically just means that someone send an invalid transaction.

**Comment by dbpatty** [comment]
Ty, I read the replies on the chats, but I was wondering if this error continues to be not problematic.
